name: Check

on:
  workflow_dispatch: {}
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
    - uses: opentofu/setup-opentofu@v2
      with:
        tofu_version_file: .opentofu-version

    - run: tofu fmt -check -recursive

    - run: tofu init -backend=false
      working-directory: ./environments/staging
    - run: tofu validate
      working-directory: ./environments/staging

    - run: tofu init -backend=false
      working-directory: ./environments/production
    - run: tofu validate
      working-directory: ./environments/production

    - run: tofu init -backend=false
      working-directory: ./environments/shared
    - run: tofu validate
      working-directory: ./environments/shared
