name: Terraform Validate

on:
  workflow_dispatch: {}
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.5.7"

    - run: terraform fmt -check -recursive

    - run: terraform init -backend=false
      working-directory: ./environments/staging
    - run: terraform validate
      working-directory: ./environments/staging

    - run: terraform init -backend=false
      working-directory: ./environments/production
    - run: terraform validate
      working-directory: ./environments/production

    - run: terraform init -backend=false
      working-directory: ./environments/shared
    - run: terraform validate
      working-directory: ./environments/shared
